-- Insert sample data for languages
INSERT INTO languages (code, name, created_at, updated_at)
VALUES ('en', 'Tiếng Anh', NOW(), NOW()),
       ('vi', 'Tiếng Việt', NOW(), NOW()),
       ('ko', 'Tiếng Hàn', NOW(), NOW()),
       ('ja', 'Tiếng Nhật', NOW(), NOW()),
       ('zh', 'Tiếng Trung', NOW(), NOW()),
       ('fr', 'Tiếng Pháp', NOW(), NOW()),
       ('de', 'Tiếng Đức', NOW(), NOW()),
       ('es', 'Tiếng Tây Ban Nha', NOW(), NOW());

-- Insert sample data for countries
INSERT INTO countries (name, created_at, updated_at)
VALUES ('Hoa Kỳ', NOW(), NOW()),
       ('Việt Nam', NOW(), NOW()),
       ('Hàn Quốc', NOW(), NOW()),
       ('Nhật Bản', NOW(), NOW()),
       ('Trung Quốc', NOW(), NOW()),
       ('Pháp', NOW(), NOW()),
       ('Đức', NOW(), NOW()),
       ('Vương quốc Anh', NOW(), NOW()),
       ('Canada', NOW(), NOW()),
       ('Úc', NOW(), NOW());

-- Insert sample movie genres
INSERT INTO movie_genres (name, created_at, updated_at)
VALUES ('Hành động', NOW(), NOW()),
       ('Phiêu lưu', NOW(), NOW()),
       ('Hài', NOW(), NOW()),
       ('Chính kịch', NOW(), NOW()),
       ('Kinh dị', NOW(), NOW()),
       ('Lãng mạn', NOW(), NOW()),
       ('Khoa học viễn tưởng', NOW(), NOW()),
       ('Kỳ ảo', NOW(), NOW()),
       ('Giật gân', NOW(), NOW()),
       ('Hoạt hình', NOW(), NOW()),
       ('Tội phạm', NOW(), NOW()),
       ('Bí ẩn', NOW(), NOW()),
       ('Gia đình', NOW(), NOW()),
       ('Tài liệu', NOW(), NOW()),
       ('Âm nhạc', NOW(), NOW());

-- Insert sample movie data
INSERT INTO movies (name, description, duration, release_date, poster_url, banner_url, trailer_url, age_rating,
                    director, actor, status, language_id, country_id, is_deleted, created_at, updated_at, is_featured)
VALUES ('Avatar: The Way of Water',
        'Đặt hơn một thập kỷ sau các sự kiện của phần phim đầu tiên, Avatar: The Way of Water bắt đầu kể câu chuyện về gia đình Sully, những rắc rối theo sau họ, những nỗ lực họ làm để bảo vệ lẫn nhau, những trận chiến họ đấu tranh để sống sót, và những bi kịch họ phải chịu đựng.',
        192, '2022-12-16', 'https://example.com/posters/avatar2.jpg', 'https://example.com/banners/avatar2_banner.jpg',
        'https://youtube.com/watch?v=d9MyW72ELq0', 13, 'James Cameron',
        'Sam Worthington, Zoe Saldana, Sigourney Weaver', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Top Gun: Maverick',
        'Sau ba mươi năm, Maverick vẫn đang đẩy giới hạn như một phi công hải quân hàng đầu, nhưng phải đối mặt với những bóng ma quá khứ khi dẫn dắt các học viên ưu tú của TOP GUN trong một nhiệm vụ đòi hỏi sự hy sinh tối thượng từ những người được chọn bay nó.',
        131, '2022-05-27', 'https://example.com/posters/topgun2.jpg', 'https://example.com/banners/topgun2_banner.jpg',
        'https://youtube.com/watch?v=qSqVVswa420', 12, 'Joseph Kosinski', 'Tom Cruise, Miles Teller, Jennifer Connelly',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Black Panther: Wakanda Forever',
        'Quốc gia Wakanda đối đầu với các thế lực thế giới can thiệp khi họ thương tiếc sự ra đi của Vua T''Challa.',
        161, '2022-11-11', 'https://example.com/posters/blackpanther2.jpg',
        'https://example.com/banners/blackpanther2_banner.jpg', 'https://youtube.com/watch?v=_Z3QKkl1WyM', 13,
        'Ryan Coogler', 'Letitia Wright, Lupita Nyong''o, Danai Gurira', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Spider-Man: No Way Home',
        'Với danh tính của Spider-Man giờ đã bị lộ, Peter nhờ Doctor Strange giúp đỡ. Khi một câu thần chú sai lầm, những kẻ thù nguy hiểm từ các thế giới khác bắt đầu xuất hiện, buộc Peter phải khám phá ý nghĩa thực sự của việc trở thành Spider-Man.',
        148, '2021-12-17', 'https://example.com/posters/spiderman_nowayhome.jpg',
        'https://example.com/banners/spiderman_nowayhome_banner.jpg', 'https://youtube.com/watch?v=JfVOs4VSpmA', 13,
        'Jon Watts', 'Tom Holland, Zendaya, Benedict Cumberbatch', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Dune',
        'Paul Atreides, một chàng trai trẻ tài năng và xuất chúng sinh ra trong một số phận vĩ đại vượt quá sự hiểu biết của anh ta, phải du hành đến hành tinh nguy hiểm nhất trong vũ trụ để đảm bảo tương lai của gia đình và dân tộc anh ta.',
        155, '2021-10-22', 'https://example.com/posters/dune.jpg', 'https://example.com/banners/dune_banner.jpg',
        'https://youtube.com/watch?v=n9xhJrPXop4', 13, 'Denis Villeneuve',
        'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Batman',
        'Khi một kẻ giết người hàng loạt tàn bạo bắt đầu sát hại các nhân vật chính trị quan trọng ở Gotham, Batman bị buộc phải điều tra sự tha hóa ẩn giấu của thành phố và đặt câu hỏi về sự liên quan của gia đình mình.',
        176, '2022-03-04', 'https://example.com/posters/thebatman.jpg',
        'https://example.com/banners/thebatman_banner.jpg', 'https://youtube.com/watch?v=mqqft2x_Aa4', 15,
        'Matt Reeves', 'Robert Pattinson, Zoë Kravitz, Paul Dano', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Doctor Strange in the Multiverse of Madness',
        'Tiến sĩ Stephen Strange niệm một câu thần chú bị cấm mở ra cánh cửa đến đa vũ trụ, bao gồm các phiên bản thay thế của chính mình, mối đe dọa đối với nhân loại quá lớn đối với sức mạnh kết hợp của Strange, Wong, và Wanda Maximoff.',
        126, '2022-05-06', 'https://example.com/posters/doctorstrange2.jpg',
        'https://example.com/banners/doctorstrange2_banner.jpg', 'https://youtube.com/watch?v=aWzlQ2N6qqg', 13,
        'Sam Raimi', 'Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor', 'ENDED', 1, 1, false, NOW(), NOW(),
        false),
       ('Thor: Love and Thunder',
        'Thor nhờ sự giúp đỡ của Valkyrie, Korg và bạn gái cũ Jane Foster để chiến đấu với Gorr the God Butcher, kẻ định làm tuyệt chủng các vị thần.',
        119, '2022-07-08', 'https://example.com/posters/thor4.jpg', 'https://example.com/banners/thor4_banner.jpg',
        'https://youtube.com/watch?v=Go8nTmfrQd8', 13, 'Taika Waititi',
        'Chris Hemsworth, Natalie Portman, Christian Bale', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Minions: The Rise of Gru',
        'Câu chuyện chưa kể về giấc mơ của một cậu bé mười hai tuổi trở thành siêu ác nhân vĩ đại nhất thế giới.', 90,
        '2022-07-01', 'https://example.com/posters/minions2.jpg', 'https://example.com/banners/minions2_banner.jpg',
        'https://youtube.com/watch?v=6DxjJzm0XNo', 0, 'Kyle Balda', 'Steve Carell, Pierre Coffin, Russell Brand',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Lightyear',
        'Trong khi dành nhiều năm cố gắng trở về nhà, Phi hành gia Không gian bị mắc kẹt Buzz Lightyear gặp một đội quân robot tàn bạo do Zurg chỉ huy đang cố gắng đánh cắp nguồn nhiên liệu của anh ta.',
        105, '2022-06-17', 'https://example.com/posters/lightyear.jpg',
        'https://example.com/banners/lightyear_banner.jpg', 'https://youtube.com/watch?v=BwPL0Md_QFQ', 0,
        'Angus MacLane', 'Chris Evans, Keke Palmer, Peter Sohn', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Jurassic World Dominion',
        'Bốn năm sau sự phá hủy Isla Nublar, khủng long giờ sống và săn mồi cùng với con người trên toàn thế giới. Sự cân bằng mong manh này sẽ định hình lại tương lai và quyết định, một lần và mãi mãi, liệu con người có còn là loài săn mồi đỉnh cao trên hành tinh mà họ giờ chia sẻ với những sinh vật đáng sợ nhất lịch sử.',
        147, '2022-06-10', 'https://example.com/posters/jurassicworld3.jpg',
        'https://example.com/banners/jurassicworld3_banner.jpg', 'https://youtube.com/watch?v=fb5ELWi-ekk', 13,
        'Colin Trevorrow', 'Chris Pratt, Bryce Dallas Howard, Laura Dern', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Fantastic Beasts: The Secrets of Dumbledore',
        'Phần thứ ba của loạt phim "Fantastic Beasts" lấy bối cảnh trong Thế giới Phù thủy do J.K. Rowling sáng tạo.',
        142, '2022-04-15', 'https://example.com/posters/fantasticbeasts3.jpg',
        'https://example.com/banners/fantasticbeasts3_banner.jpg', 'https://youtube.com/watch?v=Y9k2c0bQqYI', 13,
        'David Yates', 'Eddie Redmayne, Jude Law, Ezra Miller', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Sonic the Hedgehog 2',
        'Sau khi định cư ở Green Hills, Sonic sẵn sàng cho sự tự do hơn, và Tom cùng Maddie đồng ý để anh ở nhà khi họ đi nghỉ. Nhưng họ vừa đi khỏi, thì Tiến sĩ Robotnik trở lại, lần này với một đối tác mới, Knuckles, trong cuộc tìm kiếm một viên ngọc có sức mạnh xây dựng và phá hủy các nền văn minh.',
        122, '2022-04-08', 'https://example.com/posters/sonic2.jpg', 'https://example.com/banners/sonic2_banner.jpg',
        'https://youtube.com/watch?v=47r8FXYZWNU', 0, 'Jeff Fowler', 'Ben Schwartz, Idris Elba, Jim Carrey', 'ENDED', 1,
        1, false, NOW(), NOW(), false),
       ('The Lost City',
        'Một nhà tiểu thuyết lãng mạn ẩn dật trong chuyến lưu diễn sách với người mẫu bìa của cô bị cuốn vào một âm mưu bắt cóc đưa cả hai vào cuộc phiêu lưu rừng rậm đầy nguy hiểm.',
        112, '2022-03-25', 'https://example.com/posters/thelostcity.jpg',
        'https://example.com/banners/thelostcity_banner.jpg', 'https://youtube.com/watch?v=nfKO9rYDmE8', 13,
        'Aaron Nee', 'Sandra Bullock, Channing Tatum, Daniel Radcliffe', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Uncharted',
        'Nathan Drake thông minh đường phố được tuyển mộ bởi thợ săn kho báu kỳ cựu Victor "Sully" Sullivan để thu hồi một kho báu do Ferdinand Magellan tích lũy, và bị mất 500 năm trước bởi Nhà Moncada.',
        116, '2022-02-18', 'https://example.com/posters/uncharted.jpg',
        'https://example.com/banners/uncharted_banner.jpg', 'https://youtube.com/watch?v=eHp3MbsCbMg', 13,
        'Ruben Fleischer', 'Tom Holland, Mark Wahlberg, Antonio Banderas', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Black Widow',
        'Natasha Romanoff đối mặt với những phần tối tăm hơn trong sổ cái của cô khi một âm mưu nguy hiểm có liên hệ với quá khứ của cô nổi lên. Bị truy đuổi bởi một thế lực sẽ không dừng lại để hạ gục cô, Natasha phải đối phó với lịch sử điệp viên của mình và những mối quan hệ tan vỡ để lại phía sau từ lâu trước khi cô trở thành một Avengers.',
        134, '2021-07-09', 'https://example.com/posters/blackwidow.jpg',
        'https://example.com/banners/blackwidow_banner.jpg', 'https://youtube.com/watch?v=ybji16u608U', 13,
        'Cate Shortland', 'Scarlett Johansson, Florence Pugh, David Harbour', 'ENDED', 1, 1, false, NOW(), NOW(),
        false),
       ('Fast & Furious 9', 'Cypher nhờ sự giúp đỡ của Jakob, em trai của Dom, để trả thù Dom và đội của anh ta.', 143,
        '2021-06-25', 'https://example.com/posters/fast9.jpg', 'https://example.com/banners/fast9_banner.jpg',
        'https://youtube.com/watch?v=aSiDu3Ywi8E', 13, 'Justin Lin', 'Vin Diesel, Michelle Rodriguez, Tyrese Gibson',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('A Quiet Place Part II',
        'Sau các sự kiện tại nhà, gia đình Abbott giờ đối mặt với nỗi kinh hoàng của thế giới bên ngoài. Bị buộc phải mạo hiểm vào vùng đất chưa biết, họ nhận ra rằng những sinh vật săn bằng âm thanh không phải là mối đe dọa duy nhất rình rập ngoài con đường cát.',
        97, '2021-05-28', 'https://example.com/posters/aquietplace2.jpg',
        'https://example.com/banners/aquietplace2_banner.jpg', 'https://youtube.com/watch?v=BpdDN9d9Jio', 15,
        'John Krasinski', 'Emily Blunt, Millicent Simmonds, Cillian Murphy', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Godzilla vs. Kong',
        'Chương tiếp theo sử thi trong vũ trụ điện ảnh Monsterverse đối đầu hai biểu tượng vĩ đại nhất lịch sử điện ảnh với nhau - Godzilla đáng sợ và Kong hùng mạnh - với nhân loại bị kẹt ở giữa.',
        113, '2021-03-31', 'https://example.com/posters/godzillavskong.jpg',
        'https://example.com/banners/godzillavskong_banner.jpg', 'https://youtube.com/watch?v=odM92ap8_c0', 13,
        'Adam Wingard', 'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall', 'ENDED', 1, 1, false, NOW(), NOW(),
        false),
       ('Wonder Woman 1984',
        'Diana phải đối đầu với một đồng nghiệp làm việc và doanh nhân, kẻ khao khát sự giàu có cực đoan khiến thế giới đi theo con đường hủy diệt, sau khi một cổ vật cổ xưa ban điều ước bị mất tích.',
        151, '2020-12-25', 'https://example.com/posters/wonderwoman1984.jpg',
        'https://example.com/banners/wonderwoman1984_banner.jpg', 'https://youtube.com/watch?v=XW2E2Fnh52w', 13,
        'Patty Jenkins', 'Gal Gadot, Chris Pine, Kristen Wiig', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Matrix Resurrections',
        'Neo trở lại thế giới Ma Trận để đối mặt với những mối đe dọa mới và khám phá lại bản thân.', 148, '2021-12-22',
        'https://example.com/posters/matrix4.jpg', 'https://example.com/banners/matrix4_banner.jpg',
        'https://youtube.com/watch?v=gTE85jWNr0U', 13, 'Lana Wachowski',
        'Keanu Reeves, Carrie-Anne Moss, Yahya Abdul-Mateen II', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Encanto', 'Một cô gái có khả năng phép thuật khám phá sức mạnh thực sự của mình trong khi giúp đỡ gia đình.',
        102, '2021-11-24', 'https://example.com/posters/encanto.jpg', 'https://example.com/banners/encanto_banner.jpg',
        'https://youtube.com/watch?v=9mQbC7MtWQo', 0, 'Byron Howard',
        'Stephanie Beatriz, María Cecilia Botero, Diane Guerrero', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Shang-Chi and the Legend of the Ten Rings',
        'Shang-Chi phải đối mặt với quá khứ của mình khi được kéo vào cuộc chiến của cha anh ta.', 132, '2021-09-03',
        'https://example.com/posters/shangchi.jpg', 'https://example.com/banners/shangchi_banner.jpg',
        'https://youtube.com/watch?v=8YjFbMbfVJQ', 13, 'Destin Daniel Cretton', 'Simu Liu, Awkwafina, Tony Leung',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Eternals', 'Nhóm bất tử bảo vệ Trái Đất khỏi Deviants qua hàng ngàn năm.', 156, '2021-11-05',
        'https://example.com/posters/eternals.jpg', 'https://example.com/banners/eternals_banner.jpg',
        'https://youtube.com/watch?v=t0I0-t8SL8Q', 13, 'Chloé Zhao', 'Gemma Chan, Richard Madden, Angelina Jolie',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('No Time to Die', 'James Bond đối mặt với mối đe dọa mới từ một kẻ thù cũ.', 163, '2021-10-08',
        'https://example.com/posters/notimetodie.jpg', 'https://example.com/banners/notimetodie_banner.jpg',
        'https://youtube.com/watch?v=atn1sK1kXoo', 13, 'Cary Joji Fukunaga', 'Daniel Craig, Rami Malek, Lashana Lynch',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Venom: Let There Be Carnage', 'Eddie Brock và Venom đối mặt với kẻ thù mới Cletus Kasady.', 97, '2021-10-01',
        'https://example.com/posters/venom2.jpg', 'https://example.com/banners/venom2_banner.jpg',
        'https://youtube.com/watch?v=2mx1hBsiR9k', 17, 'Andy Serkis', 'Tom Hardy, Michelle Williams, Woody Harrelson',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Ghostbusters: Afterlife', 'Gia đình Spengler phát hiện di sản của ông nội họ.', 124, '2021-11-11',
        'https://example.com/posters/ghostbustersafterlife.jpg',
        'https://example.com/banners/ghostbustersafterlife_banner.jpg', 'https://youtube.com/watch?v=Qr0s4zM6K4E', 13,
        'Jason Reitman', 'Finn Wolfhard, Mckenna Grace, Carrie Coon', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Suicide Squad', 'Nhóm phản anh hùng thực hiện nhiệm vụ tự sát.', 132, '2021-08-05',
        'https://example.com/posters/suicidesquad.jpg', 'https://example.com/banners/suicidesquad_banner.jpg',
        'https://youtube.com/watch?v=QFp6oV0oL1w', 17, 'James Gunn', 'Margot Robbie, Idris Elba, John Cena', 'ENDED', 1,
        1, false, NOW(), NOW(), false),
       ('Free Guy', 'Một nhân vật NPC trong game video trở nên nhận thức.', 115, '2021-08-13',
        'https://example.com/posters/freeguy.jpg', 'https://example.com/banners/freeguy_banner.jpg',
        'https://youtube.com/watch?v=An7q4E3yJ0M', 13, 'Shawn Levy', 'Ryan Reynolds, Jodie Comer, Taika Waititi',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Cruella', 'Nguồn gốc của Cruella de Vil trong London những năm 1970.', 134, '2021-05-28',
        'https://example.com/posters/cruella.jpg', 'https://example.com/banners/cruella_banner.jpg',
        'https://youtube.com/watch?v=wjmCFyZrJ0w', 13, 'Craig Gillespie', 'Emma Stone, Emma Thompson, Joel Fry',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Jungle Cruise', 'Một cuộc phiêu lưu trên sông Amazon với những bí mật cổ xưa.', 127, '2021-07-30',
        'https://example.com/posters/junglecruise.jpg', 'https://example.com/banners/junglecruise_banner.jpg',
        'https://youtube.com/watch?v=6D8e0zV0k0A', 13, 'Jaume Collet-Serra',
        'Dwayne Johnson, Emily Blunt, Edgar Ramírez', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Space Jam: A New Legacy', 'LeBron James và con trai bị mắc kẹt trong thế giới Looney Tunes.', 115,
        '2021-07-16', 'https://example.com/posters/spacejam2.jpg', 'https://example.com/banners/spacejam2_banner.jpg',
        'https://youtube.com/watch?v=8Y9G7z5z0wA', 0, 'Malcolm D. Lee', 'LeBron James, Don Cheadle, Cedric Joe',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Raya and the Last Dragon', 'Raya tìm kiếm rồng cuối cùng để khôi phục hòa bình.', 107, '2021-03-05',
        'https://example.com/posters/raya.jpg', 'https://example.com/banners/raya_banner.jpg',
        'https://youtube.com/watch?v=3U0QeQ4z0wA', 0, 'Don Hall', 'Kelly Marie Tran, Awkwafina, Gemma Chan', 'ENDED', 1,
        1, false, NOW(), NOW(), false),
       ('Luca', 'Hai cậu bé biển biến thành con người ở thị trấn ven biển Ý.', 95, '2021-06-18',
        'https://example.com/posters/luca.jpg', 'https://example.com/banners/luca_banner.jpg',
        'https://youtube.com/watch?v=4U0QeQ4z0wA', 0, 'Enrico Casarosa',
        'Jacob Tremblay, Jack Dylan Grazer, Emma Berman', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Soul', 'Một nhạc sĩ jazz khám phá ý nghĩa của cuộc sống.', 100, '2020-12-25',
        'https://example.com/posters/soul.jpg', 'https://example.com/banners/soul_banner.jpg',
        'https://youtube.com/watch?v=5U0QeQ4z0wA', 0, 'Pete Docter', 'Jamie Foxx, Tina Fey, Graham Norton', 'ENDED', 1,
        1, false, NOW(), NOW(), false),
       ('Onward', 'Hai anh em elf sử dụng phép thuật để gặp lại cha.', 102, '2020-03-06',
        'https://example.com/posters/onward.jpg', 'https://example.com/banners/onward_banner.jpg',
        'https://youtube.com/watch?v=6U0QeQ4z0wA', 0, 'Dan Scanlon', 'Tom Holland, Chris Pratt, Julia Louis-Dreyfus',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Frozen II', 'Elsa khám phá nguồn gốc phép thuật của mình.', 103, '2019-11-22',
        'https://example.com/posters/frozen2.jpg', 'https://example.com/banners/frozen2_banner.jpg',
        'https://youtube.com/watch?v=7U0QeQ4z0wA', 0, 'Chris Buck', 'Idina Menzel, Kristen Bell, Jonathan Groff',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Toy Story 4', 'Woody và Buzz đi du lịch với Bonnie.', 100, '2019-06-21',
        'https://example.com/posters/toystory4.jpg', 'https://example.com/banners/toystory4_banner.jpg',
        'https://youtube.com/watch?v=8U0QeQ4z0wA', 0, 'Josh Cooley', 'Tom Hanks, Tim Allen, Annie Potts', 'ENDED', 1, 1,
        false, NOW(), NOW(), false),
       ('The Lion King', 'Simba trở thành vua của Pride Lands.', 118, '2019-07-19',
        'https://example.com/posters/lionking.jpg', 'https://example.com/banners/lionking_banner.jpg',
        'https://youtube.com/watch?v=9U0QeQ4z0wA', 0, 'Jon Favreau', 'Donald Glover, Seth Rogen, Chiwetel Ejiofor',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Aladdin', 'Aladdin và cây đèn thần gặp công chúa Jasmine.', 128, '2019-05-24',
        'https://example.com/posters/aladdin.jpg', 'https://example.com/banners/aladdin_banner.jpg',
        'https://youtube.com/watch?v=aU0QeQ4z0wA', 0, 'Guy Ritchie', 'Mena Massoud, Naomi Scott, Will Smith', 'ENDED',
        1, 1, false, NOW(), NOW(), false),
       ('Dumbo', 'Một chú voi tai lớn học bay và trở thành ngôi sao.', 112, '2019-03-29',
        'https://example.com/posters/dumbo.jpg', 'https://example.com/banners/dumbo_banner.jpg',
        'https://youtube.com/watch?v=bU0QeQ4z0wA', 0, 'Tim Burton', 'Colin Farrell, Michael Keaton, Danny DeVito',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Mary Poppins Returns', 'Mary Poppins trở lại giúp gia đình Banks.', 130, '2018-12-19',
        'https://example.com/posters/marypoppins.jpg', 'https://example.com/banners/marypoppins_banner.jpg',
        'https://youtube.com/watch?v=cU0QeQ4z0wA', 0, 'Rob Marshall', 'Emily Blunt, Lin-Manuel Miranda, Ben Whishaw',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Christopher Robin', 'Winnie the Pooh giúp Christopher Robin tìm lại niềm vui.', 104, '2018-08-03',
        'https://example.com/posters/christopherrobin.jpg', 'https://example.com/banners/christopherrobin_banner.jpg',
        'https://youtube.com/watch?v=dU0QeQ4z0wA', 0, 'Marc Forster', 'Ewan McGregor, Hayley Atwell, Bronte Carmichael',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Coco', 'Miguel khám phá thế giới người chết để theo đuổi giấc mơ âm nhạc.', 105, '2017-11-22',
        'https://example.com/posters/coco.jpg', 'https://example.com/banners/coco_banner.jpg',
        'https://youtube.com/watch?v=eU0QeQ4z0wA', 0, 'Lee Unkrich',
        'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Cars 3', 'Lightning McQueen huấn luyện để cạnh tranh với thế hệ mới.', 102, '2017-06-16',
        'https://example.com/posters/cars3.jpg', 'https://example.com/banners/cars3_banner.jpg',
        'https://youtube.com/watch?v=fU0QeQ4z0wA', 0, 'Brian Fee', 'Owen Wilson, Cristela Alonazo, Cristin Milioti',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Moana', 'Công chúa Moana khởi hành để cứu đảo của mình.', 107, '2016-11-23',
        'https://example.com/posters/moana.jpg', 'https://example.com/banners/moana_banner.jpg',
        'https://youtube.com/watch?v=gU0QeQ4z0wA', 0, 'Ron Clements', 'Auliʻi Cravalho, Dwayne Johnson, Rachel House',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Finding Dory', 'Dory tìm kiếm gia đình của mình.', 97, '2016-06-17',
        'https://example.com/posters/findingdory.jpg', 'https://example.com/banners/findingdory_banner.jpg',
        'https://youtube.com/watch?v=hU0QeQ4z0wA', 0, 'Andrew Stanton', 'Ellen DeGeneres, Albert Brooks, Ed O''Neill',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Zootopia', 'Judy Hopps và Nick Wilde điều tra âm mưu ở Zootopia.', 108, '2016-03-04',
        'https://example.com/posters/zootopia.jpg', 'https://example.com/banners/zootopia_banner.jpg',
        'https://youtube.com/watch?v=iU0QeQ4z0wA', 0, 'Byron Howard', 'Ginnifer Goodwin, Jason Bateman, Idris Elba',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Good Dinosaur', 'Arlo kết bạn với cậu bé người trong thế giới khủng long.', 93, '2015-11-25',
        'https://example.com/posters/gooddinosaur.jpg', 'https://example.com/banners/gooddinosaur_banner.jpg',
        'https://youtube.com/watch?v=jU0QeQ4z0wA', 0, 'Peter Sohn', 'Raymond Ochoa, Jack McBrayer, Steve Zahn', 'ENDED',
        1, 1, false, NOW(), NOW(), false),
       ('Inside Out', 'Cảm xúc trong đầu Riley giúp cô đối phó với thay đổi.', 95, '2015-06-19',
        'https://example.com/posters/insideout.jpg', 'https://example.com/banners/insideout_banner.jpg',
        'https://youtube.com/watch?v=kU0QeQ4z0wA', 0, 'Pete Docter', 'Amy Poehler, Phyllis Smith, Bill Hader', 'ENDED',
        1, 1, false, NOW(), NOW(), false),
       ('Oppenheimer',
        'Bộ phim kể về cuộc đời của J. Robert Oppenheimer, nhà vật lý học dẫn dắt Dự án Manhattan trong Thế chiến II, và những hậu quả đạo đức từ việc phát triển quả bom nguyên tử.',
        180, '2023-07-21', 'https://example.com/posters/oppenheimer.jpg',
        'https://example.com/banners/oppenheimer_banner.jpg', 'https://youtube.com/watch?v=orKD6V0pJaQ', 13,
        'Christopher Nolan', 'Cillian Murphy, Emily Blunt, Matt Damon', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Barbie',
        'Barbie và Ken bị đuổi khỏi Barbie Land và đến thế giới con người, nơi họ phải đối mặt với những chân thực về bản thân và xã hội.',
        114, '2023-07-21', 'https://example.com/posters/barbie.jpg', 'https://example.com/banners/barbie_banner.jpg',
        'https://youtube.com/watch?v=xy8Slb3uM4U', 12, 'Greta Gerwig', 'Margot Robbie, Ryan Gosling, America Ferrera',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Guardians of the Galaxy Vol. 3',
        'Nhóm Vệ binh Thiên hà phải bảo vệ Rocket khỏi quá khứ đau thương của anh ta, dẫn đến một cuộc phiêu lưu đầy nguy hiểm.',
        150, '2023-05-05', 'https://example.com/posters/guardians3.jpg',
        'https://example.com/banners/guardians3_banner.jpg', 'https://youtube.com/watch?v=7gW6N9T2W6s', 13,
        'James Gunn', 'Chris Pratt, Zoe Saldaña, Dave Bautista', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Super Mario Bros. Movie',
        'Anh em Mario và Luigi được đưa vào thế giới Mushroom Kingdom để cứu công chúa Peach khỏi tay vua Bowser.', 92,
        '2023-04-05', 'https://example.com/posters/supermario.jpg', 'https://example.com/banners/supermario_banner.jpg',
        'https://youtube.com/watch?v=ccP6T0mN2wE', 0, 'Aaron Horvath', 'Chris Pratt, Anya Taylor-Joy, Charlie Day',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('John Wick: Chapter 4',
        'John Wick đối mặt với một liên minh mới của kẻ thù để giành lấy tự do, dẫn đến những cuộc chiến đẫm máu trên toàn thế giới.',
        169, '2023-03-24', 'https://example.com/posters/johnwick4.jpg',
        'https://example.com/banners/johnwick4_banner.jpg', 'https://youtube.com/watch?v=VZAG7Fz8s9A', 18,
        'Chad Stahelski', 'Keanu Reeves, Donnie Yen, Bill Skarsgård', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Ant-Man and the Wasp: Quantumania',
        'Scott Lang và gia đình khám phá Vương quốc Lượng tử, nơi họ đối mặt với nhân vật phản diện Kang.', 124,
        '2023-02-17', 'https://example.com/posters/antman3.jpg', 'https://example.com/banners/antman3_banner.jpg',
        'https://youtube.com/watch?v=ZH6_YkU3f4g', 13, 'Peyton Reed', 'Paul Rudd, Evangeline Lilly, Jonathan Majors',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Cocaine Bear', 'Một con gấu nâu trở nên điên cuồng sau khi dùng cocaine, gây ra hỗn loạn ở rừng Georgia.', 95,
        '2023-02-24', 'https://example.com/posters/cocainebear.jpg',
        'https://example.com/banners/cocainebear_banner.jpg', 'https://youtube.com/watch?v=8k4hD4z7w2Y', 17,
        'Elizabeth Banks', 'Keri Russell, Ray Liotta, Margo Martindale', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Scream VI', 'Nhóm bạn sống ở New York bị Ghostface săn đuổi một lần nữa, tiết lộ những bí mật đen tối.', 122,
        '2023-03-10', 'https://example.com/posters/scream6.jpg', 'https://example.com/banners/scream6_banner.jpg',
        'https://youtube.com/watch?v=4b5sY8z0nQ4', 17, 'Matt Bettinelli-Olpin',
        'Melissa Barrera, Jenna Ortega, Mason Gooding', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Creed III', 'Adonis Creed đối mặt với đối thủ từ quá khứ, thách thức sự nghiệp quyền anh của anh ta.', 116,
        '2023-03-03', 'https://example.com/posters/creed3.jpg', 'https://example.com/banners/creed3_banner.jpg',
        'https://youtube.com/watch?v=aO5e3uM4z0s', 13, 'Michael B. Jordan',
        'Michael B. Jordan, Tessa Thompson, Jonathan Majors', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Shazam! Fury of the Gods',
        'Billy Batson và gia đình siêu anh hùng chống lại các nữ thần Hy Lạp muốn lấy lại sức mạnh của họ.', 130,
        '2023-03-17', 'https://example.com/posters/shazam2.jpg', 'https://example.com/banners/shazam2_banner.jpg',
        'https://youtube.com/watch?v=6m6Qv7w0w0w', 13, 'David F. Sandberg', 'Zachary Levi, Asher Angel, Helen Mirren',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('65', 'Một phi hành gia bị mắc kẹt trên Trái Đất 65 triệu năm trước, chiến đấu với khủng long để sống sót.', 92,
        '2023-03-02', 'https://example.com/posters/65.jpg', 'https://example.com/banners/65_banner.jpg',
        'https://youtube.com/watch?v=3v3y4z0k8z0', 13, 'Scott Beck', 'Adam Driver, Ariana Greenblatt', 'ENDED', 1, 1,
        false, NOW(), NOW(), false),
       ('Tetris', 'Câu chuyện về việc cấp phép trò chơi Tetris, với những âm mưu gián điệp và cuộc chiến pháp lý.', 118,
        '2023-03-31', 'https://example.com/posters/tetris.jpg', 'https://example.com/banners/tetris_banner.jpg',
        'https://youtube.com/watch?v=9s4z0k8z0k8', 13, 'Jon S. Baird', 'Taron Egerton, Nikita Efremov, Sofia Lebedeva',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Dungeons & Dragons: Honor Among Thieves',
        'Một nhóm bất hảo lấy một báu vật bị đánh cắp, dẫn đến cuộc phiêu lưu kỳ ảo.', 134, '2023-03-31',
        'https://example.com/posters/dnd.jpg', 'https://example.com/banners/dnd_banner.jpg',
        'https://youtube.com/watch?v=8s4z0k8z0k8', 13, 'Jonathan Goldstein',
        'Chris Pine, Michelle Rodriguez, Justice Smith', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Pope''s Exorcist',
        'Cha Gabriele Amorth, nhà trừ tà của Vatican, điều tra một trường hợp bị ám ở Tây Ban Nha.', 103, '2023-04-14',
        'https://example.com/posters/popeexorcist.jpg', 'https://example.com/banners/popeexorcist_banner.jpg',
        'https://youtube.com/watch?v=2s4z0k8z0k8', 17, 'Julius Avery', 'Russell Crowe, Daniel Zovatto, Alex Esso',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Evil Dead Rise', 'Một người phụ nữ phát hiện ra Necronomicon, giải phóng các thế lực ác quỷ lên gia đình cô.',
        139, '2023-04-21', 'https://example.com/posters/evildeadrise.jpg',
        'https://example.com/banners/evildeadrise_banner.jpg', 'https://youtube.com/watch?v=3s4z0k8z0k8', 18,
        'Lee Cronin', 'Lily Sullivan, Alyssa Sutherland, Gabrielle Echols', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Mafia Mamma', 'Một người mẹ ngoại ô trở thành ông trùm mafia sau khi cha cô qua đời.', 101, '2023-05-12',
        'https://example.com/posters/mafiamamma.jpg', 'https://example.com/banners/mafiamamma_banner.jpg',
        'https://youtube.com/watch?v=4s4z0k8z0k8', 13, 'Catherine Hardwicke',
        'Toni Collette, Monica Bellucci, Rob Huebel', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Covenant',
        'Một người lính Mỹ được cứu bởi người phiên dịch Afghanistan và giờ anh ta quay lại cứu anh ta.', 123,
        '2023-04-21', 'https://example.com/posters/covenant.jpg', 'https://example.com/banners/covenant_banner.jpg',
        'https://youtube.com/watch?v=5s4z0k8z0k8', 17, 'Guy Ritchie', 'Jake Gyllenhaal, Dar Salim, Alexander Ludwig',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Air', 'Câu chuyện về cách Nike ký hợp đồng với Michael Jordan để tạo ra dòng giày Air Jordan.', 111,
        '2023-04-05', 'https://example.com/posters/air.jpg', 'https://example.com/banners/air_banner.jpg',
        'https://youtube.com/watch?v=6s4z0k8z0k8', 13, 'Ben Affleck', 'Matt Damon, Viola Davis, Jason Bateman', 'ENDED',
        1, 1, false, NOW(), NOW(), false),
       ('Renfield', 'Renfield, người hầu của Dracula, tìm cách thoát khỏi sự kiểm soát của chủ nhân.', 93, '2023-04-14',
        'https://example.com/posters/renfield.jpg', 'https://example.com/banners/renfield_banner.jpg',
        'https://youtube.com/watch?v=7s4z0k8z0k8', 17, 'Chris McKay', 'Nicolas Cage, Nicholas Hoult, Awkwafina',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Ritual Killer', 'Một giáo sư sử dụng các nghi thức cổ xưa để giải quyết các vụ giết người hàng loạt.', 93,
        '2023-03-10', 'https://example.com/posters/ritualkiller.jpg',
        'https://example.com/banners/ritualkiller_banner.jpg', 'https://youtube.com/watch?v=8s4z0k8z0k8', 17,
        'George McClashan', 'Cole Hauser, Alice Krige, Randall William Cook', 'ENDED', 1, 1, false, NOW(), NOW(),
        false),
       ('Deadpool & Wolverine',
        'Deadpool buộc phải làm việc với một Wolverine thay thế từ vũ trụ khác để cứu vũ trụ của mình.', 128,
        '2024-07-26', 'https://example.com/posters/deadpool3.jpg', 'https://example.com/banners/deadpool3_banner.jpg',
        'https://youtube.com/watch?v=9s4z0k8z0k8', 18, 'Shawn Levy', 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Inside Out 2', 'Riley bước vào tuổi dậy thì, với những cảm xúc mới như Lo âu, Ghen tị và Chán nản.', 96,
        '2024-06-14', 'https://example.com/posters/insideout2.jpg', 'https://example.com/banners/insideout2_banner.jpg',
        'https://youtube.com/watch?v=0s4z0k8z0k8', 0, 'Kelsey Mann', 'Amy Poehler, Maya Hawke, Kensington Tallman',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Despicable Me 4', 'Gru đối mặt với một kẻ thù mới, Balthazar Bratt, trong khi bảo vệ gia đình.', 95,
        '2024-07-03', 'https://example.com/posters/despicableme4.jpg',
        'https://example.com/banners/despicableme4_banner.jpg', 'https://youtube.com/watch?v=1s4z0k8z0k8', 0,
        'Chris Renaud', 'Steve Carell, Kristen Wiig, Pierre Coffin', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Twisters', 'Một thợ săn lốc xoáy đối mặt với những cơn bão lớn nhất lịch sử.', 122, '2024-07-19',
        'https://example.com/posters/twisters.jpg', 'https://example.com/banners/twisters_banner.jpg',
        'https://youtube.com/watch?v=2s4z0k8z0k8', 13, 'Lee Isaac Chung',
        'Daisy Edgar-Jones, Glen Powell, Anthony Ramos', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Longlegs', 'Một đặc vụ FBI điều tra các vụ giết người hàng loạt liên quan đến nghi lễ ma quái.', 101,
        '2024-07-12', 'https://example.com/posters/longlegs.jpg', 'https://example.com/banners/longlegs_banner.jpg',
        'https://youtube.com/watch?v=3s4z0k8z0k8', 17, 'Osgood Perkins', 'Maika Monroe, Nicolas Cage, Blair Underwood',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Fly Me to the Moon', 'Một giám đốc tiếp thị NASA dàn dựng một phiên bản giả của sứ mệnh Apollo 11.', 132,
        '2024-07-12', 'https://example.com/posters/flymetothemoon.jpg',
        'https://example.com/banners/flymetothemoon_banner.jpg', 'https://youtube.com/watch?v=4s4z0k8z0k8', 13,
        'Greg Berlanti', 'Scarlett Johansson, Channing Tatum, Ray Romano', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Fall Guy', 'Một cascadeur bị cuốn vào một âm mưu lớn khi tìm kiếm bạn diễn mất tích.', 126, '2024-05-03',
        'https://example.com/posters/fallguy.jpg', 'https://example.com/banners/fallguy_banner.jpg',
        'https://youtube.com/watch?v=5s4z0k8z0k8', 13, 'David Leitch',
        'Ryan Gosling, Emily Blunt, Aaron Taylor-Johnson', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Kingdom of the Planet of the Apes', 'Nhiều năm sau sự thống trị của Caesar, một vương quốc khỉ mới nổi lên.',
        145, '2024-05-10', 'https://example.com/posters/planetapes4.jpg',
        'https://example.com/banners/planetapes4_banner.jpg', 'https://youtube.com/watch?v=6s4z0k8z0k8', 13, 'Wes Ball',
        'Owen Teague, Freya Allan, Kevin Durand', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Furiosa: A Mad Max Saga', 'Nguồn gốc của Furiosa trước các sự kiện trong Mad Max: Fury Road.', 148,
        '2024-05-24', 'https://example.com/posters/furiosa.jpg', 'https://example.com/banners/furiosa_banner.jpg',
        'https://youtube.com/watch?v=7s4z0k8z0k8', 17, 'George Miller', 'Anya Taylor-Joy, Chris Hemsworth, Tom Burke',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Dune: Part Two', 'Paul Atreides liên minh với Fremen để chiến đấu chống lại Nhà Harkonnen.', 166, '2024-03-01',
        'https://example.com/posters/dune2.jpg', 'https://example.com/banners/dune2_banner.jpg',
        'https://youtube.com/watch?v=8s4z0k8z0k8', 13, 'Denis Villeneuve',
        'Timothée Chalamet, Zendaya, Rebecca Ferguson', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Ghostbusters: Frozen Empire', 'Các thợ săn ma trở lại New York để chống lại một mối đe dọa cổ xưa.', 115,
        '2024-03-22', 'https://example.com/posters/ghostbustersfrozen.jpg',
        'https://example.com/banners/ghostbustersfrozen_banner.jpg', 'https://youtube.com/watch?v=9s4z0k8z0k8', 13,
        'Gil Kenan', 'Paul Rudd, Carrie Coon, Finn Wolfhard', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Godzilla x Kong: The New Empire', 'Godzilla và Kong liên minh chống lại một mối đe dọa mới từ Titan.', 115,
        '2024-03-29', 'https://example.com/posters/godzillaxkong2.jpg',
        'https://example.com/banners/godzillaxkong2_banner.jpg', 'https://youtube.com/watch?v=0s4z0k8z0k8', 13,
        'Adam Wingard', 'Rebecca Hall, Brian Tyree Henry, Dan Stevens', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Kung Fu Panda 4', 'Po trở thành Linh Vương và phải tìm kiếm người kế vị, đối mặt với kẻ thù mới.', 94,
        '2024-03-08', 'https://example.com/posters/kungfupanda4.jpg',
        'https://example.com/banners/kungfupanda4_banner.jpg', 'https://youtube.com/watch?v=1s4z0k8z0k8', 0,
        'Mike Mitchell', 'Jack Black, Awkwafina, Viola Davis', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Garfield Movie', 'Garfield hợp tác với cha mình để thực hiện một vụ cướp.', 101, '2024-05-24',
        'https://example.com/posters/garfield.jpg', 'https://example.com/banners/garfield_banner.jpg',
        'https://youtube.com/watch?v=2s4z0k8z0k8', 0, 'Mark Dindal',
        'Chris Pratt, Samuel L. Jackson, Hannah Waddingham', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('IF', 'Một cô bé có khả năng nhìn thấy những người bạn tưởng tượng của trẻ em.', 104, '2024-05-17',
        'https://example.com/posters/if.jpg', 'https://example.com/banners/if_banner.jpg',
        'https://youtube.com/watch?v=3s4z0k8z0k8', 0, 'John Krasinski', 'Cailey Fleming, Ryan Reynolds, John Krasinski',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Bad Boys: Ride or Die', 'Mike và Marcus điều tra một âm mưu nhắm vào lực lượng đặc nhiệm.', 115, '2024-06-07',
        'https://example.com/posters/badboys4.jpg', 'https://example.com/banners/badboys4_banner.jpg',
        'https://youtube.com/watch?v=4s4z0k8z0k8', 13, 'Adil El Arbi', 'Will Smith, Martin Lawrence, Vanessa Hudgens',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Watchers', 'Một nghệ sĩ trẻ bị mắc kẹt trong một khu rừng Ireland với những sinh vật bí ẩn.', 101,
        '2024-06-07', 'https://example.com/posters/thewatchers.jpg',
        'https://example.com/banners/thewatchers_banner.jpg', 'https://youtube.com/watch?v=5s4z0k8z0k8', 15,
        'Ishana Night Shyamalan', 'Dakota Fanning, Georgina Campbell, Oliver Finnegan', 'ENDED', 1, 1, false, NOW(),
        NOW(),
        false),
       ('A Quiet Place: Day One', 'Nguồn gốc của cuộc xâm lược âm thanh, theo dõi một phụ nữ ở New York.', 99,
        '2024-06-28', 'https://example.com/posters/aquietplacedayone.jpg',
        'https://example.com/banners/aquietplacedayone_banner.jpg', 'https://youtube.com/watch?v=6s4z0k8z0k8', 15,
        'Michael Sarnoski', 'Lupita Nyong''o, Joseph Quinn, Alex Wolff', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Bikeriders', 'Một câu lạc bộ xe máy biến từ nhóm hàng xóm thành băng đảng tội phạm.', 116, '2024-06-21',
        'https://example.com/posters/bikeriders.jpg', 'https://example.com/banners/bikeriders_banner.jpg',
        'https://youtube.com/watch?v=7s4z0k8z0k8', 17, 'Jeff Nichols', 'Jodie Comer, Austin Butler, Tom Hardy', 'ENDED',
        1, 1, false, NOW(), NOW(), false),
       ('The Crow', 'Một người đàn ông được hồi sinh để trả thù cho cái chết của anh ta và vị hôn thê.', 111,
        '2024-08-23', 'https://example.com/posters/thecrow.jpg', 'https://example.com/banners/thecrow_banner.jpg',
        'https://youtube.com/watch?v=8s4z0k8z0k8', 17, 'Rupert Sanders', 'Bill Skarsgård, FKA twigs, Danny Huston',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Borderlands', 'Một nhóm những kẻ ngoài vòng pháp luật tìm kiếm một đứa trẻ có sức mạnh.', 102, '2024-08-09',
        'https://example.com/posters/borderlands.jpg', 'https://example.com/banners/borderlands_banner.jpg',
        'https://youtube.com/watch?v=9s4z0k8z0k8', 13, 'Eli Roth', 'Cate Blanchett, Kevin Hart, Jamie Lee Curtis',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Kraven the Hunter', 'Nguồn gốc của Kraven, một thợ săn trở thành kẻ thù của Spider-Man.', 127, '2024-12-13',
        'https://example.com/posters/kraven.jpg', 'https://example.com/banners/kraven_banner.jpg',
        'https://youtube.com/watch?v=0s4z0k8z0k8', 17, 'J.C. Chandor',
        'Aaron Taylor-Johnson, Ariana DeBose, Russell Crowe', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Moana 2', 'Moana khởi hành trên một cuộc hành trình mới để khôi phục trái tim của Te Fiti.', 100, '2024-11-27',
        'https://example.com/posters/moana2.jpg', 'https://example.com/banners/moana2_banner.jpg',
        'https://youtube.com/watch?v=1s4z0k8z0k8', 0, 'David G. Derrick Jr.', 'Auliʻi Cravalho, Dwayne Johnson',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Wicked', 'Sự hình thành tình bạn giữa Elphaba và Glinda tại Shiz University.', 140, '2024-11-20',
        'https://example.com/posters/wicked.jpg', 'https://example.com/banners/wicked_banner.jpg',
        'https://youtube.com/watch?v=2s4z0k8z0k8', 0, 'Jon M. Chu', 'Cynthia Erivo, Ariana Grande, Jonathan Bailey',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Gladiator II', 'Lucius, con trai của Lucilla, trở thành chiến binh trong đấu trường La Mã.', 155, '2024-11-22',
        'https://example.com/posters/gladiator2.jpg', 'https://example.com/banners/gladiator2_banner.jpg',
        'https://youtube.com/watch?v=3s4z0k8z0k8', 17, 'Ridley Scott', 'Paul Mescal, Pedro Pascal, Denzel Washington',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Mufasa: The Lion King', 'Câu chuyện nguồn gốc của Mufasa, cha của Simba.', 119, '2024-12-20',
        'https://example.com/posters/mufasa.jpg', 'https://example.com/banners/mufasa_banner.jpg',
        'https://youtube.com/watch?v=4s4z0k8z0k8', 0, 'Barry Jenkins', 'Aaron Pierre, Kelvin Harrison Jr., Seth Rogen',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Sonic the Hedgehog 3', 'Sonic, Tails và Knuckles chiến đấu chống lại Shadow.', 95, '2024-12-20',
        'https://example.com/posters/sonic3.jpg', 'https://example.com/banners/sonic3_banner.jpg',
        'https://youtube.com/watch?v=5s4z0k8z0k8', 0, 'Jeff Fowler', 'Ben Schwartz, Colleen Shaughnessey, Idris Elba',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Nosferatu', 'Một bản làm lại của phim kinh điển về bá tước Orlok.', 132, '2024-12-25',
        'https://example.com/posters/nosferatu.jpg', 'https://example.com/banners/nosferatu_banner.jpg',
        'https://youtube.com/watch?v=6s4z0k8z0k8', 17, 'Robert Eggers',
        'Bill Skarsgård, Lily-Rose Depp, Nicholas Hoult', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Avatar 3', 'Tiếp nối câu chuyện của gia đình Sully trên Pandora.', 180, '2025-12-19',
        'https://example.com/posters/avatar3.jpg', 'https://example.com/banners/avatar3_banner.jpg',
        'https://youtube.com/watch?v=7s4z0k8z0k8', 13, 'James Cameron',
        'Sam Worthington, Zoe Saldana, Sigourney Weaver', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Mission: Impossible - The Final Reckoning', 'Ethan Hunt đối mặt với mối đe dọa cuối cùng từ The Entity.', 130,
        '2025-05-23', 'https://example.com/posters/missionimpossible8.jpg',
        'https://example.com/banners/missionimpossible8_banner.jpg', 'https://youtube.com/watch?v=8s4z0k8z0k8', 13,
        'Christopher McQuarrie', 'Tom Cruise, Hayley Atwell, Ving Rhames', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Captain America: Brave New World', 'Sam Wilson đối mặt với những mối đe dọa toàn cầu mới.', 120, '2025-02-14',
        'https://example.com/posters/captainamerica4.jpg', 'https://example.com/banners/captainamerica4_banner.jpg',
        'https://youtube.com/watch?v=9s4z0k8z0k8', 13, 'Julius Onah', 'Anthony Mackie, Danny Ramirez, Shira Haas',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Thunderbolts*', 'Nhóm phản anh hùng của Marvel thực hiện nhiệm vụ bí mật.', 121, '2025-07-25',
        'https://example.com/posters/thunderbolts.jpg', 'https://example.com/banners/thunderbolts_banner.jpg',
        'https://youtube.com/watch?v=0s4z0k8z0k8', 13, 'Jake Schreier', 'Florence Pugh, Sebastian Stan, David Harbour',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Blade', 'Blade chiến đấu chống lại các vampire trong thế giới hiện đại.', 110, '2025-11-07',
        'https://example.com/posters/blade.jpg', 'https://example.com/banners/blade_banner.jpg',
        'https://youtube.com/watch?v=1s4z0k8z0k8', 17, 'Yann Demange', 'Mahershala Ali, Mia Goth, Delroy Lindo',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Fantastic Four: The First Steps', 'Gia đình Fantastic Four khám phá không gian và nhận sức mạnh.', 120,
        '2025-05-02', 'https://example.com/posters/fantasticfour.jpg',
        'https://example.com/banners/fantasticfour_banner.jpg', 'https://youtube.com/watch?v=2s4z0k8z0k8', 13,
        'Matt Shakman', 'Pedro Pascal, Vanessa Kirby, Joseph Quinn', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('Snow White', 'Bản làm lại live-action của Bạch Tuyết và bảy chú lùn.', 105, '2025-03-21',
        'https://example.com/posters/snowwhite.jpg', 'https://example.com/banners/snowwhite_banner.jpg',
        'https://youtube.com/watch?v=3s4z0k8z0k8', 0, 'Marc Webb', 'Rachel Zegler, Gal Gadot, Andrew Burnap', 'ENDED',
        1, 1, false, NOW(), NOW(), false),
       ('Mickey 17', 'Một nhân viên thay thế trên sứ mệnh thuộc địa hóa sao Hỏa chết đi sống lại nhiều lần.', 137,
        '2025-03-07', 'https://example.com/posters/mickey17.jpg', 'https://example.com/banners/mickey17_banner.jpg',
        'https://youtube.com/watch?v=4s4z0k8z0k8', 13, 'Bong Joon-ho', 'Robert Pattinson, Naomi Ackie, Steven Yeun',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The Smurfs Movie', 'Nhóm Smurf phiêu lưu để cứu làng của họ khỏi Gargamel.', 90, '2025-02-14',
        'https://example.com/posters/smurfs.jpg', 'https://example.com/banners/smurfs_banner.jpg',
        'https://youtube.com/watch?v=5s4z0k8z0k8', 0, 'Rihanna', 'Rihanna, Nick Offerman, Natasha Lyonne', 'ENDED', 1,
        1, false, NOW(), NOW(), false),
       ('How to Train Your Dragon', 'Bản live-action của cậu bé Viking và rồng của cậu.', 130, '2025-06-13',
        'https://example.com/posters/howtotrainyourdragon.jpg',
        'https://example.com/banners/howtotrainyourdragon_banner.jpg', 'https://youtube.com/watch?v=6s4z0k8z0k8', 0,
        'Dean DeBlois', 'Mason Thames, Nico Parker, Gerard Butler', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('28 Years Later', 'Tiếp nối loạt phim zombie với một nhóm sống sót mới.', 115, '2025-06-20',
        'https://example.com/posters/28years.jpg', 'https://example.com/banners/28years_banner.jpg',
        'https://youtube.com/watch?v=7s4z0k8z0k8', 17, 'Danny Boyle',
        'Cillian Murphy, Jodie Comer, Aaron Taylor-Johnson', 'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The SpongeBob Movie: Search for SquarePants', 'SpongeBob bị buộc tội giết người và phải trốn thoát.', 90,
        '2025-12-19', 'https://example.com/posters/spongebob3.jpg', 'https://example.com/banners/spongebob3_banner.jpg',
        'https://youtube.com/watch?v=8s4z0k8z0k8', 0, 'Derek Drymon', 'Tom Kenny, Bill Fagerbakke, Rodger Bumpass',
        'ENDED', 1, 1, false, NOW(), NOW(), false),
       ('The War of the Rohirrim', 'Một phim hoạt hình tiền truyện về Eowyn trong Trung Địa.', 120, '2024-12-13',
        'https://example.com/posters/warofrohirrim.jpg', 'https://example.com/banners/warofrohirrim_banner.jpg',
        'https://youtube.com/watch?v=9s4z0k8z0k8', 13, 'Kenji Kamiyama', 'Brian Cox, Gaia Wise, Luke Pasqualino',
        'ENDED', 1, 1, false, NOW(), NOW(), false);

-- Insert movie-genre relationships
INSERT INTO movie_movie_genres (movie_id, movie_genres_id)
VALUES
-- Avatar: The Way of Water (Hành động, Phiêu lưu, Khoa học viễn tưởng, Kỳ ảo)
(1, 1),
(1, 2),
(1, 7),
(1, 8),
-- Top Gun: Maverick (Hành động, Chính kịch)
(2, 1),
(2, 4),
-- Black Panther: Wakanda Forever (Hành động, Phiêu lưu, Khoa học viễn tưởng)
(3, 1),
(3, 2),
(3, 7),
-- Spider-Man: No Way Home (Hành động, Phiêu lưu, Khoa học viễn tưởng)
(4, 1),
(4, 2),
(4, 7),
-- Dune (Khoa học viễn tưởng, Phiêu lưu, Chính kịch)
(5, 7),
(5, 2),
(5, 4),
-- The Batman (Hành động, Tội phạm, Chính kịch, Giật gân)
(6, 1),
(6, 11),
(6, 4),
(6, 9),
-- Doctor Strange in the Multiverse of Madness (Hành động, Phiêu lưu, Kỳ ảo, Kinh dị)
(7, 1),
(7, 2),
(7, 8),
(7, 5),
-- Thor: Love and Thunder (Hành động, Phiêu lưu, Hài, Kỳ ảo)
(8, 1),
(8, 2),
(8, 3),
(8, 8),
-- Minions: The Rise of Gru (Hoạt hình, Hài, Gia đình)
(9, 10),
(9, 3),
(9, 13),
-- Lightyear (Hoạt hình, Hành động, Phiêu lưu, Gia đình)
(10, 10),
(10, 1),
(10, 2),
(10, 13),
-- Jurassic World Dominion (Hành động, Phiêu lưu, Khoa học viễn tưởng, Giật gân)
(11, 1),
(11, 2),
(11, 7),
(11, 9),
-- Fantastic Beasts: The Secrets of Dumbledore (Phiêu lưu, Gia đình, Kỳ ảo)
(12, 2),
(12, 13),
(12, 8),
-- Sonic the Hedgehog 2 (Hành động, Phiêu lưu, Hài, Gia đình)
(13, 1),
(13, 2),
(13, 3),
(13, 13),
-- The Lost City (Hành động, Phiêu lưu, Hài, Lãng mạn)
(14, 1),
(14, 2),
(14, 3),
(14, 6),
-- Uncharted (Hành động, Phiêu lưu, Giật gân)
(15, 1),
(15, 2),
(15, 9),
-- Black Widow (Hành động, Phiêu lưu, Khoa học viễn tưởng, Giật gân)
(16, 1),
(16, 2),
(16, 7),
(16, 9),
-- Fast & Furious 9 (Hành động, Tội phạm, Giật gân)
(17, 1),
(17, 11),
(17, 9),
-- A Quiet Place Part II (Chính kịch, Kinh dị, Khoa học viễn tưởng, Giật gân)
(18, 4),
(18, 5),
(18, 7),
(18, 9),
-- Godzilla vs. Kong (Hành động, Khoa học viễn tưởng, Giật gân)
(19, 1),
(19, 7),
(19, 9),
-- Wonder Woman 1984 (Hành động, Phiêu lưu, Kỳ ảo)
(20, 1),
(20, 2),
(20, 8),
-- The Matrix Resurrections (Hành động, Khoa học viễn tưởng, Giật gân)
(21, 1),
(21, 7),
(21, 9),
-- Encanto (Hoạt hình, Hài, Gia đình, Âm nhạc)
(22, 10),
(22, 3),
(22, 13),
(22, 15),
-- Shang-Chi and the Legend of the Ten Rings (Hành động, Phiêu lưu, Kỳ ảo)
(23, 1),
(23, 2),
(23, 8),
-- Eternals (Hành động, Phiêu lưu, Chính kịch, Khoa học viễn tưởng)
(24, 1),
(24, 2),
(24, 4),
(24, 7),
-- No Time to Die (Hành động, Phiêu lưu, Giật gân)
(25, 1),
(25, 2),
(25, 9),
-- Venom: Let There Be Carnage (Hành động, Khoa học viễn tưởng, Giật gân)
(26, 1),
(26, 7),
(26, 9),
-- Ghostbusters: Afterlife (Hài, Kỳ ảo, Khoa học viễn tưởng)
(27, 3),
(27, 8),
(27, 7),
-- The Suicide Squad (Hành động, Phiêu lưu, Hài, Khoa học viễn tưởng)
(28, 1),
(28, 2),
(28, 3),
(28, 7),
-- Free Guy (Hành động, Phiêu lưu, Hài, Khoa học viễn tưởng)
(29, 1),
(29, 2),
(29, 3),
(29, 7),
-- Cruella (Hài, Tội phạm, Chính kịch)
(30, 3),
(30, 11),
(30, 4),
-- Jungle Cruise (Hành động, Phiêu lưu, Hài, Kỳ ảo)
(31, 1),
(31, 2),
(31, 3),
(31, 8),
-- Space Jam: A New Legacy (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(32, 10),
(32, 2),
(32, 3),
(32, 13),
-- Raya and the Last Dragon (Hoạt hình, Hành động, Phiêu lưu, Gia đình)
(33, 10),
(33, 1),
(33, 2),
(33, 13),
-- Luca (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(34, 10),
(34, 2),
(34, 3),
(34, 13),
-- Soul (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(35, 10),
(35, 2),
(35, 3),
(35, 13),
-- Onward (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(36, 10),
(36, 2),
(36, 3),
(36, 13),
-- Frozen II (Hoạt hình, Phiêu lưu, Hài, Gia đình, Âm nhạc)
(37, 10),
(37, 2),
(37, 3),
(37, 13),
(37, 15),
-- Toy Story 4 (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(38, 10),
(38, 2),
(38, 3),
(38, 13),
-- The Lion King (Hoạt hình, Phiêu lưu, Chính kịch, Gia đình, Âm nhạc)
(39, 10),
(39, 2),
(39, 4),
(39, 13),
(39, 15),
-- Aladdin (Phiêu lưu, Hài, Gia đình, Kỳ ảo, Âm nhạc)
(40, 2),
(40, 3),
(40, 13),
(40, 8),
(40, 15),
-- Dumbo (Phiêu lưu, Gia đình, Kỳ ảo)
(41, 2),
(41, 13),
(41, 8),
-- Mary Poppins Returns (Hài, Gia đình, Kỳ ảo, Âm nhạc)
(42, 3),
(42, 13),
(42, 8),
(42, 15),
-- Christopher Robin (Phiêu lưu, Hài, Chính kịch, Gia đình)
(43, 2),
(43, 3),
(43, 4),
(43, 13),
-- Coco (Hoạt hình, Phiêu lưu, Hài, Gia đình, Kỳ ảo)
(44, 10),
(44, 2),
(44, 3),
(44, 13),
(44, 8),
-- Cars 3 (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(45, 10),
(45, 2),
(45, 3),
(45, 13),
-- Moana (Hoạt hình, Phiêu lưu, Hài, Gia đình, Âm nhạc)
(46, 10),
(46, 2),
(46, 3),
(46, 13),
(46, 15),
-- Finding Dory (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(47, 10),
(47, 2),
(47, 3),
(47, 13),
-- Zootopia (Hoạt hình, Hành động, Phiêu lưu, Hài, Tội phạm, Gia đình)
(48, 10),
(48, 1),
(48, 2),
(48, 3),
(48, 11),
(48, 13),
-- The Good Dinosaur (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(49, 10),
(49, 2),
(49, 3),
(49, 13),
-- Inside Out (Hoạt hình, Phiêu lưu, Hài, Chính kịch, Gia đình)
(50, 10),
(50, 2),
(50, 3),
(50, 4),
(50, 13),
-- Oppenheimer (Chính kịch, Tài liệu, Bí ẩn) - Lưu ý: Biography ~ Chính kịch/Tài liệu, History ~ Bí ẩn
(51, 4),
(51, 14),
(51, 12),
-- Barbie (Phiêu lưu, Hài, Kỳ ảo)
(52, 2),
(52, 3),
(52, 8),
-- Guardians of the Galaxy Vol. 3 (Hành động, Phiêu lưu, Hài, Khoa học viễn tưởng)
(53, 1),
(53, 2),
(53, 3),
(53, 7),
-- The Super Mario Bros. Movie (Hoạt hình, Phiêu lưu, Gia đình, Kỳ ảo)
(54, 10),
(54, 2),
(54, 13),
(54, 8),
-- John Wick: Chapter 4 (Hành động, Tội phạm, Giật gân)
(55, 1),
(55, 11),
(55, 9),
-- Ant-Man and the Wasp: Quantumania (Hành động, Phiêu lưu, Hài, Khoa học viễn tưởng)
(56, 1),
(56, 2),
(56, 3),
(56, 7),
-- Cocaine Bear (Hài, Kinh dị, Giật gân)
(57, 3),
(57, 5),
(57, 9),
-- Scream VI (Kinh dị, Bí ẩn, Giật gân)
(58, 5),
(58, 12),
(58, 9),
-- Creed III (Hành động, Chính kịch)
(59, 1),
(59, 4),
-- Shazam! Fury of the Gods (Hành động, Phiêu lưu, Hài, Gia đình, Kỳ ảo)
(60, 1),
(60, 2),
(60, 3),
(60, 13),
(60, 8),
-- 65 (Hành động, Khoa học viễn tưởng, Giật gân)
(61, 1),
(61, 7),
(61, 9),
-- Tetris (Tài liệu, Chính kịch, Giật gân)
(62, 14),
(62, 4),
(62, 9),
-- Dungeons & Dragons: Honor Among Thieves (Hành động, Phiêu lưu, Hài, Kỳ ảo)
(63, 1),
(63, 2),
(63, 3),
(63, 8),
-- The Pope's Exorcist (Kinh dị, Giật gân)
(64, 5),
(64, 9),
-- Evil Dead Rise (Kinh dị, Giật gân)
(65, 5),
(65, 9),
-- Mafia Mamma (Hành động, Hài)
(66, 1),
(66, 3),
-- The Covenant (Hành động, Chính kịch, Giật gân)
(67, 1),
(67, 4),
(67, 9),
-- Air (Tài liệu, Chính kịch, Hành động) - Sport ~ Hành động
(68, 14),
(68, 4),
(68, 1),
-- Renfield (Hài, Kỳ ảo, Kinh dị)
(69, 3),
(69, 8),
(69, 5),
-- The Ritual Killer (Hành động, Tội phạm, Giật gân)
(70, 1),
(70, 11),
(70, 9),
-- Deadpool & Wolverine (Hành động, Phiêu lưu, Hài, Khoa học viễn tưởng)
(71, 1),
(71, 2),
(71, 3),
(71, 7),
-- Inside Out 2 (Hoạt hình, Phiêu lưu, Hài, Chính kịch, Gia đình)
(72, 10),
(72, 2),
(72, 3),
(72, 4),
(72, 13),
-- Despicable Me 4 (Hoạt hình, Hành động, Phiêu lưu, Hài, Gia đình)
(73, 10),
(73, 1),
(73, 2),
(73, 3),
(73, 13),
-- Twisters (Hành động, Phiêu lưu, Chính kịch, Giật gân)
(74, 1),
(74, 2),
(74, 4),
(74, 9),
-- Longlegs (Kinh dị, Giật gân)
(75, 5),
(75, 9),
-- Fly Me to the Moon (Hài, Lãng mạn)
(76, 3),
(76, 6),
-- The Fall Guy (Hành động, Hài, Chính kịch)
(77, 1),
(77, 3),
(77, 4),
-- Kingdom of the Planet of the Apes (Hành động, Phiêu lưu, Khoa học viễn tưởng)
(78, 1),
(78, 2),
(78, 7),
-- Furiosa: A Mad Max Saga (Hành động, Phiêu lưu, Khoa học viễn tưởng, Giật gân)
(79, 1),
(79, 2),
(79, 7),
(79, 9),
-- Dune: Part Two (Hành động, Phiêu lưu, Chính kịch, Khoa học viễn tưởng)
(80, 1),
(80, 2),
(80, 4),
(80, 7),
-- Ghostbusters: Frozen Empire (Hành động, Phiêu lưu, Hài, Kỳ ảo)
(81, 1),
(81, 2),
(81, 3),
(81, 8),
-- Godzilla x Kong: The New Empire (Hành động, Phiêu lưu, Khoa học viễn tưởng)
(82, 1),
(82, 2),
(82, 7),
-- Kung Fu Panda 4 (Hoạt hình, Hành động, Phiêu lưu, Hài, Gia đình)
(83, 10),
(83, 1),
(83, 2),
(83, 3),
(83, 13),
-- The Garfield Movie (Hoạt hình, Phiêu lưu, Hài, Gia đình)
(84, 10),
(84, 2),
(84, 3),
(84, 13),
-- IF (Hài, Chính kịch, Gia đình, Kỳ ảo)
(85, 3),
(85, 4),
(85, 13),
(85, 8),
-- Bad Boys: Ride or Die (Hành động, Hài, Giật gân)
(86, 1),
(86, 3),
(86, 9),
-- The Watchers (Kinh dị, Bí ẩn, Giật gân)
(87, 5),
(87, 12),
(87, 9),
-- A Quiet Place: Day One (Chính kịch, Kinh dị, Khoa học viễn tưởng)
(88, 4),
(88, 5),
(88, 7),
-- The Bikeriders (Tội phạm, Chính kịch)
(89, 11),
(89, 4),
-- The Crow (Hành động, Kỳ ảo, Giật gân)
(90, 1),
(90, 8),
(90, 9),
-- Borderlands (Hành động, Phiêu lưu, Khoa học viễn tưởng)
(91, 1),
(91, 2),
(91, 7),
-- Kraven the Hunter (Hành động, Phiêu lưu, Giật gân)
(92, 1),
(92, 2),
(92, 9),
-- Moana 2 (Hoạt hình, Phiêu lưu, Hài, Gia đình, Âm nhạc)
(93, 10),
(93, 2),
(93, 3),
(93, 13),
(93, 15),
-- Wicked (Phiêu lưu, Chính kịch, Gia đình, Kỳ ảo, Âm nhạc)
(94, 2),
(94, 4),
(94, 13),
(94, 8),
(94, 15),
-- Gladiator II (Hành động, Phiêu lưu, Chính kịch)
(95, 1),
(95, 2),
(95, 4),
-- Mufasa: The Lion King (Hoạt hình, Phiêu lưu, Chính kịch, Gia đình, Âm nhạc)
(96, 10),
(96, 2),
(96, 4),
(96, 13),
(96, 15),
-- Sonic the Hedgehog 3 (Hành động, Phiêu lưu, Hài, Gia đình, Khoa học viễn tưởng)
(97, 1),
(97, 2),
(97, 3),
(97, 13),
(97, 7),
-- Nosferatu (Kinh dị)
(98, 5),
-- Avatar 3 (Hành động, Phiêu lưu, Kỳ ảo, Khoa học viễn tưởng)
(99, 1),
(99, 2),
(99, 8),
(99, 7),
-- Mission: Impossible - The Final Reckoning (Hành động, Phiêu lưu, Giật gân)
(100, 1),
(100, 2),
(100, 9);



-- Insert sample data for ticket booking flow
-- SubTitles
INSERT INTO subtitles (code, name, created_at, updated_at)
VALUES ('VI', 'Tiếng Việt', NOW(), NOW()),
       ('EN', 'English', NOW(), NOW()),
       ('KO', 'Korean', NOW(), NOW()),
       ('JA', 'Japanese', NOW(), NOW()),
       ('ZH', 'Chinese', NOW(), NOW());

-- Room Types
INSERT INTO room_types (name, description, created_at, updated_at, active)
VALUES ('2D', 'Phòng chiếu tiêu chuẩn', NOW(), NOW(), true),
       ('3D', 'Phòng chiếu VIP cao cấp', NOW(), NOW(), true),
       ('IMAX', 'Phòng chiếu IMAX', NOW(), NOW(), true);

-- Seat Types
INSERT INTO seat_types (name, description, created_at, updated_at, active)
VALUES ('Standard', 'Ghế tiêu chuẩn', NOW(), NOW(), true),
       ('VIP', 'Ghế VIP', NOW(), NOW(), true);

-- Rooms
INSERT INTO rooms (name, room_type_id, status, created_at, updated_at, rows_count, columns_count)
VALUES ('Phòng 1', 1, 'ACTIVE', NOW(), NOW(), 10, 12),
       ('Phòng 2', 1, 'ACTIVE', NOW(), NOW(), 10, 12),
       ('Phòng 3', 2, 'ACTIVE', NOW(), NOW(), 10, 12),
       ('Phòng 4', 3, 'ACTIVE', NOW(), NOW(), 10, 12),
       ('Phòng 5', 1, 'ACTIVE', NOW(), NOW(), 10, 12),
       ('Phòng VIP 1', 2, 'ACTIVE', NOW(), NOW(), 10, 12),
       ('Phòng IMAX 1', 3, 'ACTIVE', NOW(), NOW(), 10, 12),
       ('Phòng 4DX 1', 1, 'ACTIVE', NOW(), NOW(), 10, 12);

-- Ghế cho Phòng 1 (2D - 10x8 = 80 ghế)
INSERT INTO seats (seat_row, seat_column, status, room_id, seat_type_id, created_at, updated_at)
VALUES
-- Row A (1-10)
('A', '1', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '2', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '3', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '4', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '5', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '6', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '7', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '8', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '9', 'AVAILABLE', 1, 1, NOW(), NOW()),
('A', '10', 'AVAILABLE', 1, 1, NOW(), NOW()),
-- Row B (1-10)
('B', '1', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '2', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '3', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '4', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '5', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '6', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '7', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '8', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '9', 'AVAILABLE', 1, 1, NOW(), NOW()),
('B', '10', 'AVAILABLE', 1, 1, NOW(), NOW()),
-- Row C (1-10) - Một số ghế đã đặt để test
('C', '1', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '2', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '3', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '4', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '5', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '6', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '7', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '8', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '9', 'AVAILABLE', 1, 1, NOW(), NOW()),
('C', '10', 'AVAILABLE', 1, 1, NOW(), NOW()),
-- Row D (1-10)
('D', '1', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '2', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '3', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '4', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '5', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '6', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '7', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '8', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '9', 'AVAILABLE', 1, 1, NOW(), NOW()),
('D', '10', 'AVAILABLE', 1, 1, NOW(), NOW()),
-- Row E (1-10) - Ghế VIP
('E', '1', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '2', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '3', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '4', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '5', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '6', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '7', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '8', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '9', 'AVAILABLE', 1, 2, NOW(), NOW()),
('E', '10', 'AVAILABLE', 1, 2, NOW(), NOW()),
-- Row F (1-10)
('F', '1', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '2', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '3', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '4', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '5', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '6', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '7', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '8', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '9', 'AVAILABLE', 1, 1, NOW(), NOW()),
('F', '10', 'AVAILABLE', 1, 1, NOW(), NOW()),
-- Row G (1-10)
('G', '1', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '2', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '3', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '4', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '5', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '6', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '7', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '8', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '9', 'AVAILABLE', 1, 1, NOW(), NOW()),
('G', '10', 'AVAILABLE', 1, 1, NOW(), NOW()),
-- Row H (1-10)
('H', '1', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '2', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '3', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '4', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '5', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '6', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '7', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '8', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '9', 'AVAILABLE', 1, 1, NOW(), NOW()),
('H', '10', 'AVAILABLE', 1, 1, NOW(), NOW());

-- Ghế cho Phòng 2 (3D - 10x8 = 80 ghế)
INSERT INTO seats (seat_row, seat_column, status, room_id, seat_type_id, created_at, updated_at)
VALUES
-- Row A (1-10)
('A', '1', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '2', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '3', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '4', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '5', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '6', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '7', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '8', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '9', 'AVAILABLE', 2, 1, NOW(), NOW()),
('A', '10', 'AVAILABLE', 2, 1, NOW(), NOW()),
-- Row B (1-10)
('B', '1', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '2', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '3', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '4', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '5', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '6', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '7', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '8', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '9', 'AVAILABLE', 2, 1, NOW(), NOW()),
('B', '10', 'AVAILABLE', 2, 1, NOW(), NOW()),
-- Row C (1-10) - Một số ghế đã đặt để test
('C', '1', 'BOOKED', 2, 1, NOW(), NOW()),
('C', '2', 'BOOKED', 2, 1, NOW(), NOW()),
('C', '3', 'AVAILABLE', 2, 1, NOW(), NOW()),
('C', '4', 'AVAILABLE', 2, 1, NOW(), NOW()),
('C', '5', 'AVAILABLE', 2, 1, NOW(), NOW()),
('C', '6', 'AVAILABLE', 2, 1, NOW(), NOW()),
('C', '7', 'AVAILABLE', 2, 1, NOW(), NOW()),
('C', '8', 'AVAILABLE', 2, 1, NOW(), NOW()),
('C', '9', 'AVAILABLE', 2, 1, NOW(), NOW()),
('C', '10', 'AVAILABLE', 2, 1, NOW(), NOW()),
-- Row D (1-10)
('D', '1', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '2', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '3', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '4', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '5', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '6', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '7', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '8', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '9', 'AVAILABLE', 2, 1, NOW(), NOW()),
('D', '10', 'AVAILABLE', 2, 1, NOW(), NOW()),
-- Row E (1-10) - Ghế VIP
('E', '1', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '2', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '3', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '4', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '5', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '6', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '7', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '8', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '9', 'AVAILABLE', 2, 2, NOW(), NOW()),
('E', '10', 'AVAILABLE', 2, 2, NOW(), NOW()),
-- Row F (1-10)
('F', '1', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '2', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '3', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '4', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '5', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '6', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '7', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '8', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '9', 'AVAILABLE', 2, 1, NOW(), NOW()),
('F', '10', 'AVAILABLE', 2, 1, NOW(), NOW()),
-- Row G (1-10)
('G', '1', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '2', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '3', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '4', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '5', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '6', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '7', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '8', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '9', 'AVAILABLE', 2, 1, NOW(), NOW()),
('G', '10', 'AVAILABLE', 2, 1, NOW(), NOW()),
-- Row H (1-10)
('H', '1', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '2', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '3', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '4', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '5', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '6', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '7', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '8', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '9', 'AVAILABLE', 2, 1, NOW(), NOW()),
('H', '10', 'AVAILABLE', 2, 1, NOW(), NOW());

-- ShowTimes
INSERT INTO showtimes (start_time, end_time, room_id, movie_id, subtitle_id, created_at, updated_at)
VALUES
-- Today's shows
('2024-12-19 09:00:00', '2024-12-19 12:00:00', 1, 1, 1, NOW(), NOW()), -- Avatar: The Way of Water
('2024-12-19 09:00:00', '2024-12-19 12:00:00', 2, 1, 1, NOW(), NOW()),
('2024-12-19 09:00:00', '2024-12-19 12:00:00', 3, 1, 1, NOW(), NOW()),
('2024-12-19 13:00:00', '2024-12-19 15:30:00', 1, 2, 1, NOW(), NOW()), -- Top Gun: Maverick
('2024-12-19 16:00:00', '2024-12-19 18:40:00', 1, 3, 1, NOW(), NOW()), -- Black Panther: Wakanda Forever
('2024-12-19 19:00:00', '2024-12-19 21:30:00', 1, 4, 1, NOW(), NOW()), -- Spider-Man: No Way Home
('2024-12-19 22:00:00', '2024-12-20 00:30:00', 1, 5, 1, NOW(), NOW()), -- Dune
-- Tomorrow's shows
('2024-12-20 09:00:00', '2024-12-20 12:00:00', 2, 1, 1, NOW(), NOW()),
('2024-12-20 13:00:00', '2024-12-20 15:30:00', 2, 2, 1, NOW(), NOW()),
('2024-12-20 16:00:00', '2024-12-20 18:40:00', 2, 3, 1, NOW(), NOW()),
('2024-12-20 19:00:00', '2024-12-20 21:30:00', 2, 4, 1, NOW(), NOW()),
('2024-12-20 22:00:00', '2024-12-21 00:30:00', 2, 5, 1, NOW(), NOW()),
-- VIP Room shows
('2024-12-19 20:00:00', '2024-12-19 23:00:00', 3, 1, 1, NOW(), NOW()),
('2024-12-20 20:00:00', '2024-12-20 23:00:00', 3, 2, 1, NOW(), NOW()),
-- IMAX shows
('2024-12-19 14:00:00', '2024-12-19 17:00:00', 4, 1, 1, NOW(), NOW()),
('2024-12-20 14:00:00', '2024-12-20 17:00:00', 4, 2, 1, NOW(), NOW());


-- ShowTimes
INSERT INTO showtimes (start_time, end_time, room_id, movie_id, subtitle_id, created_at, updated_at)
VALUES
-- Today's shows
('2025-10-23 09:00:00', '2025-10-23 12:00:00', 1, 1, 1, NOW(), NOW()), -- Avatar: The Way of Water
('2025-10-23 09:00:00', '2025-10-23 12:00:00', 2, 1, 1, NOW(), NOW()),
('2025-10-19 09:00:00', '2025-10-23 12:00:00', 3, 1, 1, NOW(), NOW()),
('2025-10-23 13:00:00', '2025-10-23 15:30:00', 1, 2, 1, NOW(), NOW()), -- Top Gun: Maverick
('2025-10-23 16:00:00', '2025-10-23 18:40:00', 1, 3, 1, NOW(), NOW()), -- Black Panther: Wakanda Forever
('2025-10-23 19:00:00', '2025-10-23 21:30:00', 1, 4, 1, NOW(), NOW()), -- Spider-Man: No Way Home
('2025-10-23 22:00:00', '2025-10-23 00:30:00', 1, 5, 1, NOW(), NOW()), -- Dune
-- Tomorrow's shows
('2025-10-23 09:00:00', '2025-10-23 12:00:00', 2, 1, 1, NOW(), NOW()),
('2025-10-23 13:00:00', '2025-10-23 15:30:00', 2, 2, 1, NOW(), NOW()),
('2025-10-23 16:00:00', '2025-12-23 18:40:00', 2, 3, 1, NOW(), NOW()),
('2025-10-23 19:00:00', '2025-10-23 21:30:00', 2, 4, 1, NOW(), NOW()),
('2025-10-23 22:00:00', '2025-10-23 00:30:00', 2, 5, 1, NOW(), NOW()),
-- VIP Room shows
('2025-10-23 20:00:00', '2025-10-23 23:00:00', 3, 1, 1, NOW(), NOW()),
('2025-10-23 20:00:00', '2025-10-23 23:00:00', 3, 2, 1, NOW(), NOW()),
-- IMAX shows
('2025-10-23 14:00:00', '2025-10-23 17:00:00', 4, 1, 1, NOW(), NOW()),
('2025-10-23 14:00:00', '2025-10-23 17:00:00', 4, 2, 1, NOW(), NOW());

INSERT INTO showtimes (start_time, end_time, room_id, movie_id, subtitle_id, created_at, updated_at)
VALUES ('2025-10-23 14:00:00', '2025-10-23 17:00:00', 1, 1, 1, NOW(), NOW()),
       ('2025-10-23 14:00:00', '2025-10-23 17:00:00', 2, 1, 1, NOW(), NOW());